# Generated by Django 5.2.6 on 2025-10-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=30)),
                ('person_mail', models.EmailField(max_length=30)),
            ],
        ),
    ]
