# Generated by Django 4.2.26 on 2025-12-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('building_name', models.CharField(max_length=100, verbose_name='Bina Adı/Tanımı')),
                ('score_year', models.IntegerField(choices=[(30, '2019 ve sonrası (Yeni Yönetmelik)'), (20, '2000 - 2018 arası'), (5, '1980 - 1999 arası'), (0, '1980 öncesi')], verbose_name='Bina Yaşı')),
                ('score_ground', models.IntegerField(choices=[(20, 'Kayalık / Sert Zemin'), (10, 'Normal / Sıkı Toprak'), (0, 'Dolgu Zemin / Dere Yatağı / Yumuşak')], verbose_name='Zemin Durumu')),
                ('score_soft_story', models.IntegerField(choices=[(15, 'Giriş katı konut (Duvarlar mevcut)'), (0, 'Giriş katı dükkan/mağaza (Geniş camekanlı)')], verbose_name='Giriş Kat Durumu')),
                ('score_damage', models.IntegerField(choices=[(15, 'Görünür hasar/çatlak yok'), (8, 'Sıva çatlakları / Kılcal çatlaklar'), (0, 'Kolonlarda derin çatlak / Demir paslanması (Korozyon)')], verbose_name='Hasar Durumu')),
                ('score_floor', models.IntegerField(choices=[(10, '1 - 3 Katlı'), (5, '4 - 7 Katlı'), (3, '8 Kat ve üzeri')], verbose_name='Kat Sayısı')),
                ('score_shape', models.IntegerField(choices=[(10, 'Simetrik (Kare/Dikdörtgen)'), (5, 'Düzensiz (L Tipi, U Tipi, Girintili)')], verbose_name='Bina Şekli')),
            ],
        ),
    ]
