# Generated by Django 4.2.26 on 2025-12-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagess', '0002_buildingassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingassessment',
            name='building_name',
            field=models.CharField(max_length=100, verbose_name='Building Name/ID'),
        ),
        migrations.AlterField(
            model_name='buildingassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='buildingassessment',
            name='score_damage',
            field=models.IntegerField(choices=[(15, 'No visible damage/cracks'), (8, 'Hairline cracks / Plaster cracks'), (0, 'Deep cracks in columns / Rusted iron (Corrosion)')], verbose_name='Current Damage Status'),
        ),
        migrations.AlterField(
            model_name='buildingassessment',
            name='score_floor',
            field=models.IntegerField(choices=[(10, '1 - 3 Floors'), (5, '4 - 7 Floors'), (3, '8 Floors and above')], verbose_name='Number of Floors'),
        ),
        migrations.AlterField(
            model_name='buildingassessment',
            name='score_ground',
            field=models.IntegerField(choices=[(20, 'Rocky / Hard Ground'), (10, 'Normal / Firm Soil'), (0, 'Fill / Riverbed / Soft Soil')], verbose_name='Ground Condition'),
        ),
        migrations.AlterField(
            model_name='buildingassessment',
            name='score_shape',
            field=models.IntegerField(choices=[(10, 'Symmetrical (Square/Rectangle)'), (5, 'Irregular (L-Shape, U-Shape, Recessed)')], verbose_name='Building Shape'),
        ),
        migrations.AlterField(
            model_name='buildingassessment',
            name='score_soft_story',
            field=models.IntegerField(choices=[(15, 'Residential Entry (Walls present)'), (0, 'Commercial Entry (Large glass windows/Shop)')], verbose_name='Ground Floor Status (Soft Story)'),
        ),
        migrations.AlterField(
            model_name='buildingassessment',
            name='score_year',
            field=models.IntegerField(choices=[(30, '2019 and later (New Regulations)'), (20, 'Between 2000 - 2018'), (5, 'Between 1980 - 1999'), (0, 'Before 1980')], verbose_name='Building Age'),
        ),
    ]
